### ISSUE TITLE
Misleading documentation or bug - custom toast width

### ISSUE THREAD

**Issue by tecoad** [emilkowalski/sonner#630]
I noticed this [Headless / TailwindCSS](https://sonner.emilkowal.ski/styling#headless-/-tailwind-css) example from the docs, uses this class for the parent div:

```html
<div className="flex rounded-lg bg-white shadow-lg ring-1 ring-black/5 w-full md:max-w-[364px] items-center p-4">
```

However, it seems counter intuitive, because the parent div doesnt sets itself as 100% in this case:

```css
[data-sonner-toast] {
  --y: translateY(100%);
  --lift-amount: calc(var(--lift) * var(--gap));
  z-index: var(--z-index);
  position: absolute;
  opacity: 0;
  transform: var(--y);
  touch-action: none;
  transition: transform 400ms, opacity 400ms, height 400ms, box-shadow 200ms;
  box-sizing: border-box;
  outline: none;
  overflow-wrap: anywhere;
}
```

So in order of full-width to work in the custom component we have to:

```ts
<Toaster
position="bottom-center"
toastOptions={{
	className: 'w-full',
}}
/>
```

Is this undocumented or any reason to be like that @emilkowalski ?
