### ISSUE TITLE
backdrop-filter: blur() not applied during will-change & transition

### ISSUE THREAD

**Issue by tom2strobl** [emilkowalski/sonner#87]
Hi there,

first of all – I don't expect this to be resolved on this repositories level as it's basically a browser-implementation thing. I just wanted to write this down for anyone else trying to do a similar thing and searching through issues.

`will-change` prevents `backdrop-filter: blur()` from being applied. That's easy to circumvent through:

```
[data-sonner-toast] {
  will-change: initial;
}
```

But while the css transition of `transition: transform 0.4s, opacity 0.4s, height 0.4s, box-shadow 0.2s;` is happening, it appears non-rendered. Trying out setting `transition: none` has no flash of unblurred backdrop, so it's really only during said transition (but that would obviously remove all the animations, which obviously is far worse).

Here's a quick demo video (scrub to see more clearly):

https://github.com/emilkowalski/sonner/assets/557074/354c0283-da8d-4fa8-a270-94e938adb059

After playing around a little, it seems that any opacity change messes with the backdrop-filter, see this codepen `.modal:hover` where the commented out opacity change makes everything work fine, but as soon as opacity is in the mix, it refuses to render properly.

So what I'm guessing is that since opacity is used extensively throughout it's also not really feasible to try catch to catch all opacity changes with overrides, so I'd say this is just simply not possible with the current implementation and not enough of a case to urge any kind of change either.

Also, just as an expreriment trying to be clever like this doesn't make the blur work during transition:
```scss
[data-sonner-toast] {
  transition: transform 0.4s, height 0.4s, box-shadow 0.2s;
  &[data-swiping='true'] {
    transition: none;
  }
  & > * {
    opacity: 1 !important;
    transition: initial;
  }
  &[data-removed='true'][data-front='false'][data-swipe-out='false'][data-expanded='false'] {
    opacity: 1;
    transition: transform 500ms;
  }
}
```

Btw I'm closing this issue straight away – it's really first and foremost meant as an endpoint for people that search.
